var GAME_LEVELS = [
  ["                                                                                ",
   "                                                                                ",
   "                                                                                ",
   "                                                                                ",
   "                                                                                ",
   "                                                                                ",
   "                                                                                ",
   "                                                        xxxx!!!!xxx             ",
   "                                                           xxvxx                ",
   "                                                                                ",
   "                                                                                ",
   "                                        o                                    x  ",
   "  xx                                 o xxx            o                      x  ",
   "  x             g                    xxx x            xxxx                   x  ",
   "  x            xx               xxx  x   x        o                        o x  ",
   "  x          xx     o           x x  x   x       xxx                         x  ",
   "  x  @     xx       x           x x  x   x                u                  x  ",
   "  xxxxxxxxxx!!!!!!!!!!!xxxxxxxxxx x!!x   x!!!!xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx  ",
   "           x!!!!!!!!!!!x          x!!x   x!!!!x                                 ",
   "           x!!!!!!!!!!!x          xxxx   x!!!!x                                 ",
   "           x!!!!!!!!!!!x                 x!!!!x                                 ",
   "           xxxxxxxxxxxxx                 xxxxxx                                 ",
   "                                                                                ",
   "                                                                                "],
  ["                                                                                                                  ",
   "                                                                                                                  ",
   "                                                                                                                  ",
   "                                                                                                                  ",
   "                                                                                                                  ",
   "                                              x!!!!!!x                                                            ",
   "                                              x!!!!!!x                                                            ",
   "                                              x!!!!!!x                                                            ",
   "                                              xxxxvxxx                                                            ",
   "                                                                                                                  ",
   "                                                                                                                  ",
   "                oo                                                                                                ",
   "            x   xxx   x                              x                     x                                      ",
   "            x!!!!!!!!!xxx   o                        x                     x                                      ",
   "            x!!!!!!!!!xx  xxxx     g                 x!!!!!!!!!!!!!!!!!!!!1x                                      ",
   "            x!!!!!!!!!xx         xxxxx       xxxx    x!!!!!!!!!!!!!!!!!!!!!x                                      ",
   "            xxvxxvxxvxxx      o         xx     x     x!!!!!!!!!!!!!!!!!!!!!x                                      ",
   "                       x   xxxxxx              x     xxxvxxxxxvxxxxvxxxxvxxx                                      ",
   "                       x                       x     x                     x           o                          ",
   "                       x             xxxxxxxxxxx     x                     x        xxxxxxxxxx                    ",
   "     @                 x          xxx          x     x                     x        x        x                    ",
   "xxxxxxxxxxxxxx         x         x             x            o                    xxxx        x                    ",
   "             x         x       xxx             x         u     o                    x        x        oo          ",
   "             x         x      xx               xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx        xxxxxxxxxxxxxxxxxxxxx",
   "             x       o x    xxxx                                                                                  ",
   "             x      xxxxx     xx                                                                                  ",
   "             x         x       x                                                                                  ",
   "             xxx               x                                                                                  ",
   "             x                 x                                                                                  ",
   "             xxxxxxxxxxxxxxxxxxx                                                                                  "],
  ["                                                                                                              ",
   "                                                                                                              ",
   "                                                                                                              ",
   "                                                                                                              ",
   "                                                                                                              ",
   "                                                                                                              ",
   "                                                                                                              ",
   "                                                                                                              ",
   "                                                                                                              ",
   "                                                                                                              ",
   "                                                                                                              ",
   "  xxx                                                                                                    xxx  ",
   "  x x                                                                                                    x x  ",
   "  x                                                                                                        x  ",
   "  x                                                                                  o                     x  ",
   "  x                                                                                xxxxxx                  x  ",
   "  x                     o                                            xxxxxxx                               x  ",
   "  x              o   xxxxxxx                        xxxxxxxxxx                                             x  ",
   "  x         xxxxxxxxxxxxxxxx                      g x!!!!!!!!x              o                              x  ",
   "  xxxxxx             x!!!!!x                 o xxxxxx!!!!!!!!x           xxxxxxxxx                         x  ",
   "  x                  xxxvxxx               xxxxx!!!!!!!!!!!!!x                                        o    x  ",
   "  x      @                           o     x!!!!!!!!!!!!!!!!!x o                         u                 x  ",
   "  xxxxxxxxxxxxxxxxxxxxxxxxxxxxx  x   x   xxxxxxxxxvxxxvxxvxxxxxxxxx  xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx  ",
   "                              x!!!!!!!!!!x       x            xxxxx  x                                        ",
   "                              x!!!!!!!!!!x       x                   x                                        ",
   "                              x!!!!!!!!!!x       x  o                x                                        ",
   "                              xxxxxxxxxxxx       xxxxxxxxxxxxxxxxxxxxx                                        "],
  ["                                                                                                              ",
   "                                                                                                              ",
   "                                                                                                              ",
   "                                                                                                              ",
   "                                                                                                              ",
   "                                                                                                              ",
   "                                                                                                              ",
   "                                                                                                              ",
   "                                                                                                              ",
   "                                                                                                              ",
   "                                                                                                              ",
   "                                                                                                              ",
   "                                                                                                              ",
   "                                                                                                              ",
   "                          o                                                                                   ",
   "                     x!!!xxx!!!xxxx                                                                           ",
   "                     x!!!!!!!!!x               o                        x!!!!!!!x                             ",
   "                     x!!!!!!!!!x       xxxxxxxxxx     xxxx              =!!!!!!!x                             ",
   "                     x!!!!!!!!!x  x!!!!!!!!!!!!!!!!!!!!!x  xxxxx        x!!!!!!!x                             ",
   "                     xxxxvxxxxvx  x!!!!!!!!!!!!!!!!!!!!!x               x!!!!!!!x                             ",
   "                                  xxxxxxxxxxxxxxxxxxxxxxx        x      xxxxvxxxx                             ",
   "                                                                 xx                                           ",
   "                                                                xxxx                                          ",
   "!!x                      o                                     xxxxx                                          ",
   "!!x                    xxxxx                                 xxxxxxxx                   ooo                   ",
   "!!x                               x                         xxxxxxxxxxxx          xxxxxxxxxxxxxxxxxxxxx       ",
   "!!=           xxxxxxxx            x                        xxxxxxxxxxxxxx         x!!!!!!!!!!!!!!!!!!!=       ",
   "!!x   xxxxx                       x             g         xxxxxxxxxxxxxxxxx u     x!!!!!!!!!!!!!!!!!!!x   o   ",
   "!!x @                       xxxxxxx      xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx",
   "!!xxxxxxxxxxxxx!!!!!!!!!!!!!x     x    xxx                                                                    ",
   "              x!!!!!!!!!!!!!x     =      x                                                                    ",
   "              x!!!!!!!!!!!!!x     x  o   x                                                                    ",
   "              xxxxxxxxxxxxxxx     xxxxxxxx                                                                    ",
   "                                                                                                              "]
];

if (typeof module != "undefined" && module.exports)
  module.exports = GAME_LEVELS;
